[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "aiofiles==24.1.0",
    "alembic==1.15.2",
    "asyncpg==0.30.0",
    "bcrypt==4.3.0",
    "chromadb==1.0.8",
    "cryptography==44.0.2",
    "edge-tts==7.0.2",
    "email-validator==2.2.0",
    "faiss-cpu==1.11.0",
    "fastapi[standard]==0.115.9",
    "faster-whisper==1.1.1",
    "ffmpeg-python==0.2.0",
    "httpx==0.28.1",
    "ipykernel==6.29.5",
    "jupyter==1.1.1",
    "langchain==0.3.25",
    "langchain-community==0.3.24",
    "langchain-core==0.3.59",
    "langchain-ollama>=0.3.2",
    "langgraph==0.4.1",
    "librosa==0.11.0",
    "loguru==0.7.3",
    "notebook==7.4.1",
    "numpy==2.2.5",
    "ollama==0.4.8",
    "orjson==3.10.18",
    "pandas==2.2.3",
    "passlib[bcrypt]==1.7.4",
    "psycopg2-binary==2.9.10",
    "pyaudio==0.2.14",
    "pydantic==2.11.4",
    "pydantic-settings==2.9.1",
    "pypdf==5.4.0",
    "pytest==8.3.5",
    "pytest-asyncio==0.26.0",
    "python-docx==1.1.2",
    "python-dotenv==1.1.0",
    "python-jose[cryptography]==3.4.0",
    "requests==2.32.3",
    "chardet==5.2.0",
    "scikit-learn==1.6.1",
    "sentence-transformers==4.1.0",
    "soundfile==0.13.1",
    "sqlalchemy==2.0.40",
    "tenacity==9.1.2",
    "torch==2.7.0",
    "tqdm==4.67.1",
    "unstructured==0.17.2",
    "uvicorn[standard]==0.34.2",
]
